#![feature(decl_macro)]
#[macro_use]
extern crate rocket;

use rocket::{response::status::BadRequest, State};

use std::collections::HashMap;
use std::str::FromStr;
use std::sync::{Arc, Mutex, RwLock};

struct SessionsMap(RwLock<HashMap<SessionUuid, Arc<Mutex<Session>>>>);

type SessionUuid = u128;

struct Session {
    creator_identity: ClientIdentity,
    players: Vec<ClientIdentity>,
}

impl Session {
    fn new_with_creator(creator_identity: ClientIdentity) -> Self {
        Self {
            creator_identity,
            players: vec![creator_identity],
        }
    }

    fn add_player(&mut self, identity: ClientIdentity) {
        if self.players.iter().filter(|i| i.0 == identity.0).next().is_none() {
            self.players.push(identity);
        }
    }

    fn get_game_state_view(&self) -> ClientGameStateView {
        ClientGameStateView {
            number_of_players: self.players.len() as u8,
        }
    }
}

#[derive(serde::Serialize)]
struct ClientGameStateView {
    number_of_players: u8,
}

#[derive(Clone, Copy)]
struct ClientIdentity(u128);

#[rocket::async_trait]
impl<'v> rocket::form::FromFormField<'v> for ClientIdentity {
    fn from_value(field: rocket::form::ValueField<'v>) -> rocket::form::Result<'v, Self> {
        match u128::from_str(field.value) {
            Ok(identity) => Ok(ClientIdentity(identity)),
            Err(_) => Err(rocket::form::Error::validation("could not parse client identity"))?,
        }
    }

    fn default() -> Option<Self> {
        None
    }
}

// NOTE: all requests should include a `X-Identity` header with a persistent identity generated by
// the client.

/// Creates a new session and sends the random code to the client.
/// Once created, client subscribes to the session's websocket.
#[get("/create-room?<identity>")]
fn create_room(identity: ClientIdentity, sessions: &State<SessionsMap>, ws: ws::WebSocket) -> ws::Channel<'static> {
    let random_code: u128 = 123456789; // TODO actually generate this randomly
    let session = Arc::new(Mutex::new(Session::new_with_creator(identity)));
    sessions
        .0
        .write()
        .unwrap()
        .insert(random_code, Arc::clone(&session));

    manage_game_socket(ws, identity, session)
}

/// Joins an existing session using its random code.
/// Once joined, client subscribes to the session's websocket.
#[get("/join-room?<identity>&<room>")]
fn join_room(
    identity: ClientIdentity,
    room: String,
    sessions: &State<SessionsMap>,
    ws: ws::WebSocket,
) -> Result<ws::Channel<'static>, BadRequest<String>> {
    let random_code = match u128::from_str(&room) {
        Ok(code) => code,
        Err(_) => return Err(BadRequest("couldn't parse room ID".to_string())),
    };
    let sessions = sessions.0.read().unwrap();
    if let Some(session) = sessions.get(&random_code) {
        session.lock().unwrap().add_player(identity);
        Ok(manage_game_socket(ws, identity, Arc::clone(session)))
    } else {
        return Err(BadRequest("session does not exist".to_string()));
    }
}

fn manage_game_socket(ws: ws::WebSocket, identity: ClientIdentity, session: Arc<Mutex<Session>>) -> ws::Channel<'static> {
    use rocket::futures::{SinkExt, StreamExt};
    use ws::Message;

    ws.channel(move |mut stream| {
        Box::pin(async move {
            let _identity = identity;
            let session = session;
            let gamestate = session.lock().unwrap().get_game_state_view();
            stream.send(Message::Text(serde_json::to_string(&gamestate).unwrap())).await.unwrap();
            while let Some(message) = stream.next().await {
                let _ = stream.send(message?).await;
            }

            Ok(())
        })
    })
}

#[rocket::launch]
fn rocket() -> _ {
    let sessions = SessionsMap(RwLock::new(HashMap::new()));
    rocket::build()
        .manage(sessions)
        .mount("/", routes![create_room, join_room])
}
