// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";

export type ClientGameState = { state: "Lobby", content: { is_host: boolean, } } | { state: "Answering", content: { question: string, started_at: bigint, you_voted: boolean, } } | { state: "Voting", content: { answers: Array<Answer>, } };