// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientGameState = { state: "Lobby", content: { is_host: boolean, } } | { state: "Answering", content: { question: string, started_at: bigint, } };