// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientIdentity } from "./ClientIdentity";

export interface Session { creator_identity: ClientIdentity, players: Array<ClientIdentity>, }