# Use the official Rust image with the nightly toolchain as a base
FROM rustlang/rust:nightly

# Set the working directory
WORKDIR /app

# Set the environment variable
ENV AIGENT_BASE_URL=https://127.0.0.1:5934

# Copy the source code to the working directory
COPY backstab/ .
COPY aimongus_types ../aimongus_types
# Install any needed dependencies and build the application
RUN cargo build --release

# Expose the WebSocket port
EXPOSE 8000

# Define the command to run the application
CMD ["cargo",  "run", "--release"]
