-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.votes FROM authenticated;
REVOKE ALL ON TABLE public.votes FROM postgres;
REVOKE ALL ON TABLE public.votes FROM service_role;
GRANT ALL ON TABLE public.votes TO authenticated;

GRANT ALL ON TABLE public.votes TO service_role;

GRANT ALL ON TABLE public.votes TO postgres;

CREATE OR REPLACE VIEW public.answers_with_player_games
 AS
 SELECT a.id,
    a.created_at,
    a.question,
    a.answer,
    a.player,
    a.is_bot_answer,
    pg.random_player_number
   FROM answers a
     JOIN player_games pg ON a.player = pg.player AND (a.question IN ( SELECT q.id
           FROM questions q
          WHERE q.game = pg.game));

ALTER TABLE public.answers_with_player_games
    OWNER TO postgres;

GRANT ALL ON TABLE public.answers_with_player_games TO authenticated;
GRANT ALL ON TABLE public.answers_with_player_games TO postgres;
GRANT ALL ON TABLE public.answers_with_player_games TO anon;
GRANT ALL ON TABLE public.answers_with_player_games TO service_role;
