// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { SessionId } from "./SessionId";

export interface Answer { answer: string, number_of_votes: number, players_who_voted: Array<Player>, is_me: boolean, answer_id: SessionId, }