// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { VoteResult } from "./VoteResult";

export interface Answer { answer: string, number_of_votes: number, voting_result: VoteResult | null, is_me: boolean, answer_id: SessionId, }