// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export interface ChatMessage { sender: SessionId, time_sent: bigint, message: string, }