// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientGameState } from "./ClientGameState";

export interface ClientGameStateView { number_of_players: number, current_turn: number, game_state: ClientGameState, me: number, room_code: string, }