// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ClientGameState } from "./ClientGameState";
import type { Player } from "./Player";
import type { SessionId } from "./SessionId";

export interface ClientGameStateView { number_of_players: number, players: Array<Player>, current_turn: number, game_state: ClientGameState, me: SessionId, room_code: string, messages: Array<ChatMessage>, }