// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export interface Player { random_unique_id: SessionId, score: number, username: string, emoji: string, is_host: boolean, }