// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Points { guessing_the_bot: number, not_thinking_you_are_the_bot: number, }