// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { Points } from "./Points";
import type { SessionId } from "./SessionId";

export interface VoteResult { answerer: SessionId, answer: Answer, players_who_voted: Array<SessionId>, points: Points, }